### ISSUE TITLE
Transformer cannot be trained

### ISSUE THREAD

**Issue by Shadow-zbw** [Ighina/MultiModalSA#3]
When I set the Transfomer and Attention to true, the training had a dimensional error :the query and batchsize in multi-head attention were not aligned.
`	"--data_dir": "data",
	"--exclude_audio": "FALSE",
	"--exclude_video":	"FALSE",
	"--AttentionModel": "TRUE",
	"--Transformer": "TRUE",
	"--Convolution": "FALSE",
	"--Raw": "FALSE",
	"--ModifiedAttention": "FALSE",
	"--EarlyFusion": "FALSE",
	"--LateFusion": "FALSE",
	"--TensorFusion": "FALSE",
	"--Normalise": "TRUE",`

**Comment by Ighina** [comment]
Could you provide the entire error message?

**Comment by Shadow-zbw** [comment]
`Traceback (most recent call last):
  File "Train.py", line 606, in <module>
    output = model(b_audio, b_text, b_video, audio=audio, video=video, mask=src_mask, line_len=b_len, modified_attention=modified_attentio
n)  # attention model forward pass, the modified attention is an additional option that amplify modalities other than text
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yuan_yuzhou\pap\demo\multi_model_isa\MultiModalSA-master\models.py", line 323, in forward
    enc_audio = self.audio(audio_input, line_len)[1]
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yuan_yuzhou\pap\demo\multi_model_isa\MultiModalSA-master\models.py", line 217, in forward
    output = self.transformer_encoder(src, src_key_padding_mask = mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\transformer.py", line 181, in forward
    output = mod(output, src_mask=mask, src_key_padding_mask=src_key_padding_mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\transformer.py", line 294, in forward
    key_padding_mask=src_key_padding_mask)[0]
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\functional.py", line 4785, in multi_head_attention_forward
    assert key_padding_mask.size(0) == bsz
AssertionError
`

**Comment by Shadow-zbw** [comment]
Do you have this problem when you run this code

**Comment by Ighina** [comment]
I can't download and run the code today, but I applied a modification that might do the trick.
The problem is that more recent versions of pytorch have a different way of treating the batch_first=True argument in TransformerEncoder layer. I updated the code so it actually gives the input with the batch size in second position: this way the module should be compatible both with new and older versions of pytorch.
Try to download the models.py file and substitute the one that you previously cloned and re-run the code and let me know if it works.

**Comment by Shadow-zbw** [comment]
Thanks for your answer.I have tried this.It still doesn't work.There is a device problem.The problem is as follows:
`    output = model(b_audio, b_text, b_video, audio=audio, video=video, mask=src_mask, line_len=b_len, modified_attention=modified_attentio
n)  # attention model forward pass, the modified attention is an additional option that amplify modalities other than text
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yuan_yuzhou\pap\demo\multi_model_isa\MultiModalSA-master\models.py", line 321, in forward
    enc_audio = self.audio(audio_input, line_len)[1]
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yuan_yuzhou\pap\demo\multi_model_isa\MultiModalSA-master\models.py", line 215, in forward
    output = self.transformer_encoder(src, src_key_padding_mask = mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\transformer.py", line 181, in forward
    output = mod(output, src_mask=mask, src_key_padding_mask=src_key_padding_mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\transformer.py", line 294, in forward
    key_padding_mask=src_key_padding_mask)[0]
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\modules\activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "C:\Users\Shadow\anaconda3\envs\py37torch\lib\site-packages\torch\nn\functional.py", line 4810, in multi_head_attention_forward
    float("-inf"),
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mask' in call to _th_masked_fill_bool_`

**Comment by Ighina** [comment]
Ok, I now took the time to run the Transformer model locally and I have uploaded a new version that should solve the problems you were having.
If you're curious, the problem was simply that by modifying the module before I accidentally took out the line in which the key padding mask of the transformer was moved to GPU: now the padding mask is by default added to the device of the input.

Again, download the models.py script and substitute your local copy with the new version, try to rerun everything and let me know if now everything works

**Comment by Shadow-zbw** [comment]
Okay. The problem is solved.Thank you for everything. I've learned a lot.

**Comment by Ighina** [comment]
You're welcome!
